version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    links:
      - zookeeper:zk
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[   ]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: "9093"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zk"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mygoapp:
    container_name: mygoapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    env_file:
      - "./src/.env"
    volumes:
      - "./logs:/var/log/"
      - "./:/go/src"
    links:
      - kafka
